name: onu3_server
description: A websocket game server for the onu3 project.
version: 1.0.0
repository: https://github.com/onugame/onu3-server

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^2.4.3
  uuid: ^4.4.2
  crypto: ^3.0.3
  xml: ^6.5.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
